#!/usr/bin/env bash
# ap-mode.sh — Toggle the Pi between standalone WiFi access-point mode
# and normal client mode. Usage:
#
#     sudo ./scripts/ap-mode.sh start    # broadcast SmartSake AP
#     sudo ./scripts/ap-mode.sh stop     # return to home WiFi
#     ./scripts/ap-mode.sh status        # report current mode
#
# Configuration lives in scripts/ap-config.env — edit SSID, password,
# IP range there.
#
# Reversibility: `start` writes its configs to /etc/hostapd/smartsake.conf
# and /etc/dnsmasq.d/smartsake-ap.conf. `stop` removes both and restarts
# the normal network stack (NetworkManager or wpa_supplicant + dhcpcd).
#
# Safety: if no wlan0 interface exists (e.g. running on a dev box), this
# script bails with a warning instead of touching anything.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/ap-config.env"

HOSTAPD_CONF="/etc/hostapd/smartsake.conf"
HOSTAPD_DEFAULT="/etc/default/hostapd"
DNSMASQ_CONF="/etc/dnsmasq.d/smartsake-ap.conf"
STATE_FILE="/run/smartsake-ap.state"   # records that AP is active

# ── ANSI ─────────────────────────────────────────────────────────────────
GREEN="\033[32m"; YELLOW="\033[33m"; RED="\033[31m"; DIM="\033[2m"; RESET="\033[0m"

log()  { echo -e "[ap-mode] $*"; }
ok()   { echo -e "[ap-mode] ${GREEN}$*${RESET}"; }
warn() { echo -e "[ap-mode] ${YELLOW}$*${RESET}"; }
err()  { echo -e "[ap-mode] ${RED}$*${RESET}" >&2; }

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        err "Must run as root (sudo). Try: sudo $0 $1"
        exit 1
    fi
}

require_pi() {
    if ! ip link show "$AP_IFACE" >/dev/null 2>&1; then
        err "No interface $AP_IFACE found. Are you on the Pi?"
        err "(If your wireless interface has a different name, edit AP_IFACE in $CONFIG_FILE.)"
        exit 1
    fi
}

require_pkgs() {
    local missing=()
    command -v hostapd >/dev/null 2>&1 || missing+=("hostapd")
    command -v dnsmasq >/dev/null 2>&1 || missing+=("dnsmasq")
    if [ ${#missing[@]} -gt 0 ]; then
        err "Missing packages: ${missing[*]}"
        err "Install with: sudo apt install ${missing[*]}"
        exit 1
    fi
}

load_config() {
    if [ ! -f "$CONFIG_FILE" ]; then
        err "Missing config: $CONFIG_FILE"
        exit 1
    fi
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"

    : "${AP_SSID:?AP_SSID not set in $CONFIG_FILE}"
    : "${AP_PASS:?AP_PASS not set in $CONFIG_FILE}"
    : "${AP_CHANNEL:=6}"
    : "${AP_GATEWAY:?AP_GATEWAY not set in $CONFIG_FILE}"
    : "${AP_CIDR:=24}"
    : "${AP_DHCP_START:?AP_DHCP_START not set in $CONFIG_FILE}"
    : "${AP_DHCP_END:?AP_DHCP_END not set in $CONFIG_FILE}"
    : "${AP_DHCP_LEASE:=24h}"
    : "${AP_IFACE:=wlan0}"

    # WPA2 minimum length is 8 characters
    if [ ${#AP_PASS} -lt 8 ] || [ ${#AP_PASS} -gt 63 ]; then
        err "AP_PASS must be 8-63 characters (currently ${#AP_PASS})"
        exit 1
    fi
}

write_hostapd_conf() {
    cat > "$HOSTAPD_CONF" <<EOF
# Generated by SmartSake/scripts/ap-mode.sh — do not edit by hand.
# Edit scripts/ap-config.env and re-run: sudo ./restart.sh --ap
interface=$AP_IFACE
driver=nl80211
ssid=$AP_SSID
hw_mode=g
channel=$AP_CHANNEL
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=$AP_PASS
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF
    # Point hostapd at our config
    if [ -f "$HOSTAPD_DEFAULT" ]; then
        sed -i "s|^#*DAEMON_CONF=.*|DAEMON_CONF=\"$HOSTAPD_CONF\"|" "$HOSTAPD_DEFAULT"
    else
        echo "DAEMON_CONF=\"$HOSTAPD_CONF\"" > "$HOSTAPD_DEFAULT"
    fi
}

write_dnsmasq_conf() {
    cat > "$DNSMASQ_CONF" <<EOF
# Generated by SmartSake/scripts/ap-mode.sh — do not edit by hand.
interface=$AP_IFACE
bind-dynamic
dhcp-range=$AP_DHCP_START,$AP_DHCP_END,$AP_NETMASK,$AP_DHCP_LEASE
dhcp-option=3,$AP_GATEWAY
dhcp-option=6,$AP_GATEWAY
EOF
}

stop_managed_wifi() {
    # NetworkManager / wpa_supplicant must release wlan0 before hostapd takes it.
    systemctl is-active --quiet NetworkManager 2>/dev/null && {
        log "Stopping NetworkManager (will be restored on stop)…"
        nmcli radio wifi off 2>/dev/null || true
    }
    systemctl is-active --quiet wpa_supplicant 2>/dev/null && {
        log "Stopping wpa_supplicant…"
        systemctl stop wpa_supplicant
    }
    systemctl is-active --quiet dhcpcd 2>/dev/null && {
        # Keep dhcpcd running, but tell it to ignore wlan0 — easier than full stop.
        :
    }
    ip link set "$AP_IFACE" down
}

assign_static_ip() {
    ip addr flush dev "$AP_IFACE" 2>/dev/null || true
    ip addr add "$AP_GATEWAY/$AP_CIDR" dev "$AP_IFACE"
    ip link set "$AP_IFACE" up
}

start_ap_services() {
    systemctl unmask hostapd 2>/dev/null || true
    systemctl restart hostapd
    systemctl restart dnsmasq
    sleep 1
    if ! systemctl is-active --quiet hostapd; then
        err "hostapd failed to start. journalctl -xeu hostapd"
        exit 1
    fi
    if ! systemctl is-active --quiet dnsmasq; then
        err "dnsmasq failed to start. journalctl -xeu dnsmasq"
        exit 1
    fi
}

stop_ap_services() {
    systemctl stop hostapd 2>/dev/null || true
    systemctl stop dnsmasq 2>/dev/null || true
}

restore_managed_wifi() {
    rm -f "$HOSTAPD_CONF" "$DNSMASQ_CONF"
    ip addr flush dev "$AP_IFACE" 2>/dev/null || true
    ip link set "$AP_IFACE" down 2>/dev/null || true
    ip link set "$AP_IFACE" up 2>/dev/null || true
    if systemctl list-unit-files | grep -q '^NetworkManager\.service'; then
        log "Restoring NetworkManager…"
        nmcli radio wifi on 2>/dev/null || true
        systemctl restart NetworkManager 2>/dev/null || true
    elif systemctl list-unit-files | grep -q '^wpa_supplicant\.service'; then
        log "Restoring wpa_supplicant…"
        systemctl start wpa_supplicant
    fi
    if systemctl is-active --quiet dhcpcd; then
        systemctl restart dhcpcd 2>/dev/null || true
    fi
}

cmd_start() {
    require_root start
    load_config
    require_pi
    require_pkgs

    log "Starting AP mode: SSID='$AP_SSID' on $AP_IFACE @ $AP_GATEWAY/$AP_CIDR"
    stop_managed_wifi
    write_hostapd_conf
    write_dnsmasq_conf
    assign_static_ip
    start_ap_services
    mkdir -p "$(dirname "$STATE_FILE")"
    {
        echo "ssid=$AP_SSID"
        echo "iface=$AP_IFACE"
        echo "gateway=$AP_GATEWAY"
        echo "started_at=$(date -Iseconds)"
    } > "$STATE_FILE"

    ok  "AP active. Connect to '$AP_SSID' (password: $AP_PASS) and open http://$AP_GATEWAY:8080"
}

cmd_stop() {
    require_root stop
    load_config

    if [ ! -f "$STATE_FILE" ]; then
        warn "AP not active (no $STATE_FILE). Reverting interface anyway…"
    fi

    log "Stopping AP mode…"
    stop_ap_services
    restore_managed_wifi
    rm -f "$STATE_FILE"
    ok  "Back on home WiFi (NetworkManager/wpa_supplicant restored)."
}

cmd_status() {
    load_config 2>/dev/null || true
    if [ -f "$STATE_FILE" ]; then
        echo -e "${GREEN}AP MODE ACTIVE${RESET}"
        cat "$STATE_FILE"
    else
        echo -e "${DIM}AP mode inactive (client mode).${RESET}"
    fi
    if command -v hostapd >/dev/null 2>&1; then
        if systemctl is-active --quiet hostapd 2>/dev/null; then
            echo -e "  hostapd: ${GREEN}running${RESET}"
        else
            echo -e "  hostapd: ${DIM}stopped${RESET}"
        fi
    else
        echo -e "  hostapd: ${YELLOW}not installed${RESET}"
    fi
}

case "${1:-}" in
    start)  cmd_start ;;
    stop)   cmd_stop ;;
    status) cmd_status ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        echo ""
        echo "  start   Bring up SmartSake WiFi AP (requires sudo)"
        echo "  stop    Tear down AP, return to home WiFi (requires sudo)"
        echo "  status  Show current mode (no sudo needed)"
        echo ""
        echo "Config: $CONFIG_FILE"
        exit 1
        ;;
esac
